### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by polotomato** [polotomato/protospace-37401#1]
# URL
https://protospace-37401.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう**
そのページに留まらず、エラーページに遷移してしまいます。
<img width="631" alt="スクリーンショット 2022-01-14 15 58 20" src="https://user-images.githubusercontent.com/62644781/149465083-0a604d5b-af6b-4529-a651-1951e9aa4ee2.png">


※お願い※カリキュラム内容は投稿しないようお願いいたします
今回、カリキュラムの図説が投稿されているのを確認しております。
規約にもあります通り、弊社ではカリキュラム内容の外部公開を禁止しておりますので
恐れ入りますが今後動作確認の際は別の画像を使用いただくようお願いいたします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by polotomato** [comment]
> 
レビューありがとうございます。
・空のコメント投稿後に出るエラーに対応しました。
```ruby
      # @prototype = @comment.prototype
      # @comments = @prototype.comments
      render "prototypes/show"
```
カリキュラムでは、なぜこの2行が必要かよく分かっていなかったので、あえてコメントアウトして、どこかでエラーが出ないかと期待してましたが、コメントを空欄投稿後、ページが戻ったときのテストを忘れてました。。
今ならこの2行が必要とされる意味がわかります。

・該当カリキュラム画像を削除しました。

**Comment by wakazo228** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！ **LGTM**です✨
おめでとうございます🎉

> ・該当カリキュラム画像を削除しました。

上記に関してもご対応いただきありがとうございました！削除されていることを確認いたしました。

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう(^^)

**Comment by polotomato** [comment]
ありがとうございました！
